### ISSUE TITLE
Please add source and issues links to supermarket

### ISSUE THREAD

**Issue by docwhat** [phlipper/chef-cmake#5]
It'd be nice if you added links to the source and the issues in the [supermarket](https://supermarket.chef.io/cookbooks/cmake).

Ciao!

**Comment by phlipper** [comment]
@docwhat I have added the links on the [supermarket page](https://supermarket.chef.io/cookbooks/cmake), thanks!

**Comment by docwhat** [comment]
Gracias, amigo!
